<style>
.dateFilterClass label {
    background: #e0e0e0;
}

 
</style>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1> Add New Query </h1>
    </section>
    <!-- Main content -->
    <section class="content">
 
      <div class="row">
        <!-- left column -->
        <div class="col-md-9">
          <!-- general form elements -->
          <div class="box box-primary">
          <div align="center"> <?=$this->errors;?>
		  <?php if(isset($this->successmessage) and $this->successmessage){ echo $this->successmessage; }?>
		  
		  </div>
             <!-- form start -->
            
			<form role="form" action="" method="post" id="query_form" name="query_form" enctype="multipart/form-data" class="pt-3">
			<input type="hidden" name="entrytype" value="<?=$this->userInfo->category?>">
			<input type="hidden" name="date" id="date" value="<?=date('m/d/Y')?>" class="form-control tcal" />
              <div class="box-body">
			 
			  
                <div class="row form-group entrytype">
				 
				 <div class="col-sm-3" style="display:<?=($this->userInfo->category=='PhD')?'block':'none'?>">
				  <label for="exampleInputEmail1">Query Code</label>
                   
				  <select name="query_code" id="query_code" class="form-control">
				  <option value="">Select Query Code</option>
				  <option value="GH56671" <?=($this->params['query_code']=='GH56671')?"selected":""?>>GH56671</option>
				  <option value="654QTYP" <?=($this->params['query_code']=='654QTYP')?"selected":""?>>654QTYP</option>
				  <option value="C9-987-EE" <?=($this->params['query_code']=='C9-987-EE')?"selected":""?>>C9-987-EE</option>
				  <option value="7651/09/7145" <?=($this->params['query_code']=='7651/09/7145')?"selected":""?>>7651/09/7145</option>
				  <option value="15:98716" <?=($this->params['query_code']=='15:98716')?"selected":""?>>15:98716</option>
			      <option value="E3W33BS" <?=($this->params['query_code']=='E3W33BS')?"selected":""?>>E3W33BS</option>
				  <option value="AG6521" <?=($this->params['query_code']=='AG6521')?"selected":""?>>AG6521</option>
				  <option value="F3485TK" <?=($this->params['query_code']=='F3485TK')?"selected":""?>>F3485TK</option>
 				  </select>
                  <span id="query_codeError" class="error"></span>
				  </div>
				  
				  
                  <div class="col-sm-3">
				  <label for="exampleInputEmail1">Client Name<span class="error">*</span></label>
                  <input type="text" name="name" id="name" class="form-control" value="<?php echo $this->params['name'];?>" />
                  <span id="nameError" class="error"></span>
				  </div>
				  <div class="col-sm-3">
				  <label for="exampleInputPassword1">Client Email ID<span class="error">*</span></label>
                  <input type="text" name="email_id" id="email_id" value="<?php echo $this->params['email_id'];?>" class="form-control" onchange="checkExitClientAndWebsite()" />
                  <span id="email_idError" class="error"></span>
				  </div>
				  <div class="col-sm-3">
				  <label for="exampleInputPassword1">Alternate Email ID</label>
                  <input type="text" name="alt_email_id" id="alt_email_id" value="<?php echo $this->params['alt_email_id'];?>" class="form-control" />
				  </div>
                 </div>
                 
                 <div class="row form-group entrytype">
                  <div class="col-sm-3">
				  <label for="exampleInputPassword1">Contact No.</label>
                  <input type="text" name="phone" id="phone" value="<?php echo $this->params['phone'];?>" class="form-control" /> 
				  </div>
				  <div class="col-sm-3">
				  <label for="exampleInputPassword1">Alternate  Contact No.</label>
                 <input type="text" name="alt_contact_no" id="alt_contact_no" value="<?php echo $this->params['alt_contact_no'];?>" class="form-control" /> 
				  </div>
				  
				  <div class="col-sm-3">
				  <label for="exampleInputPassword1">Location</label>
                  <select name="location" id="location" class="form-control select2">
                 <option value="">Please Select</option>
                 <?php
                 foreach($this->CountryData as $Country)
				 { ?>
					<option value="<?php echo $Country['nicename'];?>" <?php if($this->params['location']==$Country['nicename']){ ?> selected="selected" <?php }?>><?php echo $Country['nicename'];?></option> 
				<?php  }
				 ?>
                 </select>
				  </div>
				  <div class="col-sm-3">
				  <label for="exampleInputPassword1">City</label>
                 <input type="text" name="city" id="city" value="<?php echo $this->params['city'];?>" class="form-control" /> 
				  </div>
				   
                 </div>
				 
				 <div class="row form-group entrytype">
                  
				  
				  
				  <div class="col-sm-3" style="display:<?=($this->userInfo->category=='PhD')?'none':'block'?>">
				  <label for="exampleInputPassword1">Client Company</label>
				  <input type="text" name="company_name" id="company_name" value="<?php echo $this->params['company_name'];?>" class="form-control" /> 
				  
				 <span id="company_nameError" class="error"></span>
				  </div>
				  
				  <div class="col-sm-3" style="display:<?=($this->userInfo->category=='PhD')?'block':'none'?>">
				  <label for="exampleInputPassword1">Topic/Area of study</label>
                 <input type="text" name="area_of_study" id="area_of_study" value="<?php echo $this->params['area_of_study'];?>" class="form-control" /> 
				  </div>
				  
				  
				   <div class="col-sm-3">
				 <div class="form-group">
                  <label for="exampleInputPassword1">Select Tags</label>
                  <select name="tags[]" id="tags" multiple class="form-control select2" data-placeholder="Please select tag">
				  <option value="">Select Tag</option>
					 <?php
					foreach($this->tagsArr as $tag)
					{ 
					$select=''; 
					if($this->params['tags'])
					{
					if(in_array($tag['id'],$this->params['tags']))
					{
					 $select='selected';
					}
					else
					{
					$select='';	
					}
					}
					?>
					<option value="<?=$tag['id']?>" <?=$select?>><?php echo $tag['tag_name'];?></option> 	
					<?php }
					?>                               
					</select>
					<span id="tagsError" class="error"></span>
                  </div>
				 </div>
				 
				 <div class="col-sm-3">
                 <label for="remarks"> Add Generic Query</label><br>
                <label for="if_generic_query"> <input type="checkbox" name="if_generic_query" id="if_generic_query" onclick="AddGenericQuery()" value="yes"> Yes </label>
                </div>
				 
				  <div class="col-sm-3"  id="website_div">
				  <label for="exampleInputPassword1">Website<span class="error">*</span></label>
				  <?php
				  if($this->params['website'])
				 {
				  $paramWebsite=$this->params['website'];
				 }
				 else
				 {
				  $paramWebsite='emarketz.net';	 
				 }
				  
				  ?>
				  
                 <select name="website" id="website" class="form-control select2" onchange="OtherFunction();">
                 <option value="">Please Select</option>
                 <?php
				 
                 foreach($this->WebsiteData as $Website)
				 { ?>
					<option value="<?php echo $Website['id'];?>" <?php if($paramWebsite==$Website['id']){ ?> selected="selected" <?php }?> webType="<?=$Website['website_type']?>"><?php echo $Website['website'];?></option> 
				<?php  }
				 ?>
                <!-- <option value="others">Others</option>-->
                 </select>
                <span id="websiteError" class="error"></span>
				  </div>
				  <div class="col-sm-3" style="display:none;" id="other_website_div">
                 <label for="exampleInputPassword1">Other Website</label>
                 <input type="text" name="other_website" id="other_website" value="<?php echo $this->params['other_website'];?>" class="form-control" />
                   <span id="other_websiteError" class="error"></span>
				  </div>
				  
				  
				  <div class="col-sm-3">
				  <label for="exampleInputPassword1">Service</label>
                  <select name="requirement" id="requirement" class="form-control select2" onchange="otherRequirement()">
                  <option value="">Please Select</option>
				 <?php foreach($this->serviceData as $service)
				 { ?>
				  <option value="<?=$service['id']?>" <?php if($this->params['requirement']==$service['id']){ ?> selected="selected" <?php }?>><?=$service['name']?></option>	 
				<?php  }?>
				 
				 <!--<option value="Other" <?php if($this->params['requirement']=="Other"){ ?> selected="selected" <?php }?>>Other</option> -->
				 
                 </select>
				 <span id="requirementError" class="error"></span>
				  </div>
				  <div class="col-sm-3" style="display:none;" id="other_requirement_div">
                 <label for="exampleInputPassword1">Other Requirement</label>
                 <input type="text" name="other_requirement" id="other_requirement" value="<?php echo $this->params['other_requirement'];?>" class="form-control" />
				 <span id="other_requirementError" class="error"></span>
				 
				  </div>
                 </div>
				 
				 
				 <!--<div class="row form-group entrytype">-->
				  
				  
				  
              



			  <!-- </div>-->
				  
				 
				 
				 <div class="row form-group entrytype">
				  
				 
				  
				  <div class="col-sm-4">
				   <div class="form-group">
				  <label for="exampleInputPassword1">Priority</label>
                 <select name="priority" id="priority" class="form-control select2">
				 <option value="">Please Select</option>
						 <?php
                         foreach($this->priorityArr as $priority)
                         {
                         ?>
                        
                        <option value="<?php echo $priority['priority'].'|'.$priority['follow_up_day'].'|'.$priority['contact_by'];?>" <?=($priority['priority'].'|'.$priority['follow_up_day'].'|'.$priority['contact_by']==$this->params['priority'])?"selected":""?>><?php echo $priority['priority'];?></option> 
                          <?php }?>
						  
						  
						  
                                    </select>
					<span id="priorityError" class="error"></span>				
				  </div>
				  </div>
				  
				   
				  
                
				   <div class="col-sm-4 PhDDiv" style="display:<?=($this->userInfo->category=='PhD')?'block':'none'?>">
                 <label for="exampleInputPassword1">Academic Level</label>
                 <select name="academic_level" id="academic_level" class="form-control select2">
                 <option value="PHD"<?php if($this->params['academic_level']=="PHD"){ ?> selected="selected" <?php }?>>PHD</option>
                 <option value="Masters"<?php if($this->params['academic_level']=="Masters"){ ?> selected="selected" <?php }?>>Masters</option>
                 <option value="Bachelors"<?php if($this->params['academic_level']=="Bachelors"){ ?> selected="selected" <?php }?>>Bachelors</option>
                 </select>
                 </div>
				  
				  <div class="col-sm-4" style="display:none;" class="form-group">
                 <label for="exampleInputPassword1">Number of Follow up Day</label>
                 <input type="text" name="no_day" id="no_day" value="<?php //echo $this->params['no_day'];?>" class="form-control" />
				  </div>
				  
				  <div class="col-sm-4">
                 <label for="remarks">Remarks</label>
                 <textarea name="remarks" id="remarks" class="form-control" rows="1" ><?php echo $this->params['remarks'];?></textarea>
                </div>
				
				
				</div>
				
				<div class="row form-group entrytype">
				  <div class="col-sm-4">
                 <label for="remarks">Box Tag</label>
				 <select name="box_tag[]" id="box_tag" multiple class="form-control select2" data-placeholder="Please select tag">
				  <option value="">Select Tag</option>
					 <?php
					foreach($this->boxTagArr as $tag)
					{ 
					$select=''; 
					if($this->params['box_tag'])
					{
					if(in_array($tag['id'],$this->params['box_tag']))
					{
					 $select='selected';
					}
					else
					{
					$select='';	
					}
					}
					?>
					<option value="<?=$tag['id']?>" <?=$select?>><?php echo $tag['box_tag_name'];?></option> 	
					<?php }
					?>                               
					</select>
				 
				 
 				  
				 
                </div>
				  <div class="col-sm-4">
				 <label for="exampleInputPassword1">Upload File</label>
                 <div class="row" id="attachment_file">
				 
				 <div class="form-group">
                                            <div class="col-md-10"><input type="file" class="form-control" name="upload_file[]" id="upload_file1"/></div>
                                            <div class="col-md-2" id="add_more_button">
											<i style="font-size:20px;padding-top:3px;cursor:pointer;" class="fa fa-plus-circle"></i></div>
              

				 </div>
		 
				 </div>
 
                </div> 
				  
				  
                 </div>
                 
                
                
				  
				 
                </div>
				
                
				
				<div class="row form-group entrytype">
				<div class="col-sm-12">
				<div class="box-footer pull-right">
                 <input type="submit" name="submitBtn" id="submitBtn" class="btn btn-primary" value="Submit" onclick="return ValidateQueryBox();" />
				 &nbsp;&nbsp;
				  <input type="button" class="btn bg-maroon" onClick="parent.location='<?=SITEURL?>managequery/userquery'"  value="Cancel" />
              </div>
				</div>
				</div>
               
                 
              </div>
              <!-- /.box-body -->

            </form>
          
		   <div class="box box-primary" id="showAlraedyExitEmailDiv" style="display:none;">
		 <div class="table-responsive">
              <table class="table table-bordered table-striped" id="alraedyExitEmail">
              
                       
					   
					   </tbody>
              </table>
 		
		  
		  
		  </div>
		  </div>
		  </div>
          <!-- /.box -->
 

        </div>
        <!--/.col (left) -->
        <!-- right column -->
         
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>
<?php include("js/js-addquery.phtml")?>

 