<?php
$statusObj = new Managequery_Model_Status();
$this->userObj = new Manageuser_Model_Manageuser();
$this->boxQueryObj = new Managequery_Model_Boxquery();
 //echo "<pre>";
 //print_r($this->QueryUsers);
 //echo "</pre>";
?>
<div class="table-responsive">
              <table id="example1" class="table table-bordered table-striped">
              <thead>
                  <tr>
                   <th><input name="2" type="checkbox" onclick="checkAll(document.form1.check,this)" /></th>
                                 <th>Camp Title</th>
                                 <th>Camp Date</th>
                                 <th>Website</th> 
                                 <th>Assigned To</th> 
                                 <th>Status</th>
                                 <th>Total Queries</th> 
                                 <th>Created Date</th>
								 
   							</tr>
                       </thead>
                       <tbody>  
                            <?php $i=1;
							$tagsArr=array();
                          foreach($this->campaignData as $Query)
						  {   
						 
 						  ?>
                           <td><input id="check" name="checkid[]" type="checkbox" value="<?php echo $Query['id'];?>"  /></td>
						   <td><?php echo $Query['camp_title'];?> </td>
                           <td><?=date("d M, Y", strtotime($Query['camp_date']))?></td>
						   <td><?php echo $Query['website_name']; ?></td> 
                               <td><?php echo $Query['user_name'];?></td>
                               <td id="statusCol<?=$Query['id'];?>"><?php if($Query['status']==0){
								   echo "Pending";
								   if($this->userInfo->user_type=='Campaign Manager')
                                    {
								   ?>
								  <div id="LoadCompBtn<?=$Query['id'];?>"> <button type="button" class="btn btn-warning btn-sm" onclick="return ClickCompletedCampaign(<?=$Query['id'];?>)">Click for completed</button></div>
								   <?php
									}
							   }
							   else if($Query['status']==1)
							   {
								   echo "Completed";
							   }   
							   ?></td>
                               <td><a href="<?=SITEURL?>managequery/camp-query/<?=$Query['id'];?>"><?php echo count(explode(',', $Query['queryIds']));?></td>
                              
							     
 							  <td><?php echo date("d M, Y H:i", $Query['assign_campaign_date']);?> </td>
							 
							  
							</tr>
                         <?php $i++; }?>
                 
                 </tbody>
              </table>
              </div>
			  
 

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
	  /*$('#filter_date').daterangepicker();*/
	  
	   $('#example1').DataTable( {
        
		
		<?php
         if(isset($this->userInfo->id) and ($this->userInfo->user_type=='admin' or $this->userInfo->user_type=='sub-admin')){ 
		?>
		dom: 'Bfrtip',
		lengthMenu: [
            [ 50, 100, 500,1000, -1 ],
            [ '50 rows', '100 rows', '500 rows', '1000 rows', 'Show all' ]
        ],
		
		
        buttons: [
            {
                extend: 'excelHtml5',
                exportOptions: {
                    columns: ':visible'
                }
            },
		 
            'colvis',
			'pageLength'
        ],
		<?php }?>
		order: [],
columnDefs: [ { orderable: false, targets: [0] } ]
    } );
	  
 
    $(".select2").select2();
 
  });
  
  function boxQueryDetailsPopUp(query_id)
  {
$('#myModal3').modal({
			backdrop: 'static',
            keyboard: false
		});	

  $.ajax({
    type : 'POST',
    url : '<?=SITEURL?>dashboard/index/getboxquerydetails',
    data :"query_id="+query_id,
	cache:false,
	beforeSend: function()
	{
	$("#PopViewBoxQuery").html('<div style="text-align:center;"> <img style="height:150px;" src="<?=PUBLICURL?>images/pre-loader-new.gif"></div>');	
 	},
	success: function(response)
	{
	 $("#PopViewBoxQuery").html(response);
	}
  });		
  }
  
function claimBoxQuery(box_query_id)
{
	if(confirm("Are you sure you want to claim this query!"))
	{
		$.ajax({
		type : 'get',
		url : '<?=SITEURL?>managequery/index/claimeboxquery',
		data :"query_id="+box_query_id,
		cache:false,
		beforeSend: function()
		{

		},
		success: function(response)
		{
        window.location.href = "/managequery/userquery";
		}
	  });
	}
 	
}
 
function claimBoxQueryGeneric(box_query_id)
{
	if($("#website_id").val()=="")
	{
		alert("Please select website");
		return false;
	}
	if($("#website_id").val()!="")
	{
		if(confirm("Are you sure you want to claim this query!"))
		{
			$.ajax({
			type : 'post',
			url : '<?=SITEURL?>managequery/index/claimeboxquery',
			data :{query_id:box_query_id,website_id:$("#website_id").val()},
			cache:false,
			beforeSend: function()
			{
             $("#genclaimBtnLoad").html('<input type="button" class="btn btn-primary" disabled  value="Please Wait...">');
			},
			success: function(response)
			{
			window.location.href = "/managequery/userquery";
			}
		  });
		}
	}
}
</script>

 