<?php
 $date = new Zend_Date();
?>
<style>
.dateFilterClass label {
    background: #e0e0e0;
}
</style>
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1> Lead Summary </h1>
       
    </section>
 
    <!-- Main content -->
    <section class="content">
    <?php if($this->errors){ echo $this->errors;}?>
      <div class="row">
        <!-- left column -->
        <div class="col-md-9">
          <!-- general form elements -->
          <div class="box box-primary">
               <div align="center"> <?=$this->errors;?>
		  <?php if(isset($this->successmessage) and $this->successmessage){ echo $this->successmessage; }?>
		  
		  </div>
             <!-- form start -->
            <form role="form" action="" method="post" id="query_form" name="query_form" enctype="multipart/form-data">
			<input type="hidden" name="entrytype" value="<?=$this->QueryInfo['entrytype']?>">
			<input type="hidden" name="date" id="date" value="<?php echo $this->QueryInfo['date'];?>"  class="form-control tcal" >
              <div class="box-body">
                  
		 
			  
			  <!--<div class="col-sm-4">
                <div class="form-group">
                  <label for="exampleInputEmail1">Lead Code</label><br/>
				  <?php //echo $this->SummaryData->query_code;?>
                 </div>
                 </div>-->
				 <div class="col-sm-4">
				 <div class="form-group">
                  <label for="exampleInputEmail1">Client Name</label><br/>
                  <?php echo $this->SummaryData->name;?>
                 </div>
                 </div>
                 <div class="col-sm-4">
                 <div class="form-group">
                  <label for="exampleInputPassword1">Client Email ID</label><br/>
                 <?php echo $this->SummaryData->email_id;?>
                  </div>
                  </div>
                  
                   <?php
				 if($this->SummaryData->alt_email_id!=''){?>
                  <div class="col-sm-4">
                   <div class="form-group">
                  <label for="exampleInputPassword1">Alternate Email ID</label><br/>
                    <?php echo $this->SummaryData->alt_email_id;?>
                  
                   </div>
                   </div>
                   <?php
                   }
                   ?>
                 <div class="col-sm-4">
                 <div class="form-group">
                 <label for="exampleInputPassword1">Phone No.</label><br/>
                   <?php echo $this->SummaryData->phone;?>
                
				 </div>
				 </div>
				 
				 <?php
				 if($this->SummaryData->alt_contact_no!=''){?>
                 <div class="col-sm-4">
                  <div class="form-group">
                 <label for="exampleInputPassword1">Alternate  Contact No.</label><br/>
                  <?php echo $this->SummaryData->alt_contact_no;?>
                
                 </div>
                 </div>
                 <?php
                 }
                 ?>
                 
                 <div class="col-sm-4">
                  <div class="form-group">
                 <label for="exampleInputPassword1">Location</label><br/>
                  <?php echo $this->SummaryData->location;?>
               
                </div>
                </div>
                
                <?php
                if($this->SummaryData['state']!=''){?>
                <div class="col-sm-4">
                     <div class="form-group">
				  <label for="exampleInputPassword1">State</label><br/>
                 <?php echo $this->SummaryData->state;?>
				  </div>
				  </div>
				 <?php
				 }
				 ?>
				  

				<div class="col-sm-4">
                 <div class="form-group">
                 <label for="exampleInputPassword1">City</label><br/>
                  <?php echo $this->SummaryData->city;?>
                
                   </div>
                   </div>
				   
				 
				 <!-- 	<div class="col-sm-4">
				 <div class="form-group">
                  <label for="exampleInputPassword1">Select Tags</label><br/>
                  
                  <?php
					/*foreach($this->tagsArr as $tag)
					{ 
					$array= explode(",",$this->assignQuerySummaryData['tags']);
					if(in_array($tag['id'],$array))
					{
			        echo $tag['tag_name'];
					}
					
					?>
				
					<?php }
          */
					?>                               
					
                  </div>
				 </div>   -->
                  
                  
                <div class="col-sm-4">
                <div class="form-group">
                 <label for="exampleInputPassword1">Website</label><br/>
                   <?php  $this->assignQuerySummaryData->website_id;
                   if($this->assignQuerySummaryData->website_id='65'){
                       echo 'emarketz.net';
                   }
                   ?>
               
               
                </div>
                </div>
                
                  <div class="col-sm-4">
                <div class="form-group">
                 <label for="exampleInputPassword1">Category</label><br/>
                  <?php  $this->SummaryData->requirement;
                  if($this->SummaryData->requirement == '1'){
                      echo 'HRMS';
                  }
                   if($this->SummaryData->requirement == '2'){
                        echo 'ERP';
                  }
                  ?>
                  
                 </div>
                 </div>
                 
                  <div class="col-sm-4">
                  <div class="form-group">
                 <label for="exampleInputPassword1">Company Size</label><br/>
                 <?php echo $this->SummaryData->compnay_size;?>
            
                   </div>
                   </div>
                 
                  <div class="col-sm-4">
                  <div class="form-group">
                 <label for="exampleInputPassword1">Designation</label><br/>
                  <?php echo $this->SummaryData->designation_name;?>
                 
                   </div>
                   </div>
                   
                   
    
				  
                <div class="col-sm-4">
				<div class="form-group">
                 <label for="exampleInputPassword1">Priority</label><br/>
                  <?php echo $this->SummaryData->priority;?>
               
                </div>
				</div>
				 
                
               
                
              
                <div class="col-sm-4">
                 <div class="form-group">
                 <label for="exampleInputPassword1">Mode of Contact</label><br/>
                   <?php echo $this->SummaryData->academic_level;?>
               
                </div>
                </div>
               
				
               <!-- <div class="col-sm-4">
				<div class="form-group">
                 <label for="exampleInputPassword1">Requirement</label><br/>
 				  <?php //echo $this->SummaryData->remarks;?>
 				
                </div>
                </div>-->

                 

                <div class="col-sm-4">
        <div class="form-group">
                 <label for="exampleInputPassword1">Requirement Type</label><br/>
          <?php echo $this->SummaryData->requirement_type;?>
        
                </div>
                </div>

                  <?php
                  if($this->SummaryData->line_format!=''){?>
                <div class="col-sm-4">
        <div class="form-group">
                 <label for="exampleInputPassword1">Requirement Type Line Format</label><br/>
          <?php echo $this->SummaryData->line_format;?>
        
                </div>
                </div>
                <?php
              }
              ?>
            <?php
                  if($this->SummaryData->paragraph_format!=''){?>
                <div class="col-sm-4">
        <div class="form-group">
                 <label for="exampleInputPassword1">Requirement Type Paragraph Format</label><br/>
          <?php echo $this->SummaryData->paragraph_format;?>
        
                </div>
                </div>
              
              <?php
            }
            ?>
                </div>
				
				 <div class="col-sm-12">
				<?php
				foreach($this->QueryFilesData as $files)
				{ ?>
				<label for="exampleInputPassword1"><a href="<?=SITEURL?><?=$files['file_path'];?>" download><?=$files['filename'];?></a></label><br>
				<?php }
				?>
				
                </div>
				
				
 				
				
              </div>
              <!-- /.box-body -->
         
            </form>
          </div>
          <!-- /.box -->
 <div class="col-md-3">
	   <div class="box box-primary">
	   <div class="box-header with-border">
              <h3 class="box-title" style="font-weight:bold;">Today Pending Task for User`s</h3>
			    </div>
	    <div class="box-body right_bx">
		<table class="table table-bordered">
                <tbody><tr>
                   <th>User Name</th>
                  <th>Total Pending</th>
                 </tr>
				 <?php 
		$totalPendingTask=0;
		foreach($this->todayTask as $user){
		    //print_r($user);
		?>
                <tr>
                   <td><?=$user['user_name']?></td>
                  <td><?=$user['total_pending']?></td>
                 </tr>
				 <?php
     $totalPendingTask=$totalPendingTask+$user['total_pending'];
		}?>
           <tr style="font-size:15px;color:red;">
                   <td>Total Pending Task</td>
                  <td><?=$totalPendingTask?></td>
                 </tr>     
              </tbody></table>
		 
 			 
 		</div>
	   
	   </div>
	   </div>
       

        </div>
        <!--/.col (left) -->
        <!-- right column -->
         
        <!--/.col (right) -->
      </div>
      <!-- /.row -->
    </section>
    <!-- /.content -->
  </div>

