<?php
$date = new Zend_Date();
$this->userObj = new Manageuser_Model_Manageuser();
?>
<div class="col-md-12">
 <table border="1" class="box box-solid box-info" style="width:70%;margin:auto;margin-bottom: 12px;font-weight: bold;margin-top:20px;">
     <thead>
                 <tr>
           <th>User Name</th>
         <th>No. of Lead</th>
         
                 <th>Lead Addition Score</th>
                 <th>Lead Approved Score</th>
                 <th>Total Score</th>
                 <!--<th>Average Score</th>-->
            
                  
           </tr>
                 </thead>
                       <tbody>  
                          <?php $i=1;
                          foreach($this->tatScore as $score)
              {
                $min=round($score['total_minute']/$score['total_rows'],2);
                $totalQuery=$this->userObj->getTatUserQuery($score['user_id']);
                $leadapprovedscore=$this->userObj->getLeadaaprovedscore($score['user_id']);
                $LeadApprovedcnt=count($leadapprovedscore);
              ?>
                                <tr>
                <td><?=$score['username']?></td>
                <td><?=count($totalQuery)?></td>
                                
                <td><?=count($totalQuery) * 5;?></td>
                                <td><?php echo $LeadApprovedcnt * 10;?></td>
                                <td><?=$score['total_score'];?></td>
                                <!--<td><?php //echo round(($score['total_score']/$score['total_rows']),2)?></td>-->
                </tr>
                         <?php $i++; }?>
                  </tbody>
 
 
 </table>
 </div>